name: dnsfwd
version: 2.79
summary: A lightweight DHCP and caching DNS server.
description: |
  dnsfwd is a lightweight DNS, TFTP, PXE, router advertisement
  and DHCP server. It is intended to provide coupled DNS and DHCP
  service to a LAN.
architectures: [armhf]
grade: stable
confinement: strict

slots:
  content:
    content: writable-data
    write:
      - $SNAP_DATA

hooks:
  configure:
    plugs: [snapd-control]

parts:
  dnsmasq:
    plugin: cmake
    source: ../..
    configflags:
      - -DCMAKE_SNAP=dnsfwd  # N.B. Snap Name
      - -DCMAKE_VERBOSE_MAKEFILE=OFF
      - -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc-4.9
      - -DDNSFWD_CONF_FILE=/var/snap/dnsfwd/common/
    build-packages:
      - gcc
      - cmake

apps:
  dnsmasqd:
    daemon: forking
    command: dnsfwd -C "$SNAP/etc/dnsfwd.conf"
    stop-timeout: 10s
    restart-condition: always
    slots:
      - content
    plugs:
      - network
      - network-bind
      - network-control
      - process-control
      - snapd-control